package io.github.visiongem.ledger.feature.settings.category

import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import io.github.visiongem.ledger.core.base.BaseViewModel
import io.github.visiongem.ledger.core.data.domain.Category
import io.github.visiongem.ledger.core.data.domain.CategoryType
import io.github.visiongem.ledger.core.data.repo.CategoryRepository
import javax.inject.Inject
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch

@HiltViewModel
class CategoryListViewModel @Inject constructor(
    private val categoryRepository: CategoryRepository,
) : BaseViewModel() {

    val state: StateFlow<CategoryListUiState> = categoryRepository.observeAll()
        .map { all ->
            CategoryListUiState(
                expense = all.filter { it.type == CategoryType.EXPENSE },
                income = all.filter { it.type == CategoryType.INCOME },
                loading = false,
            )
        }
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(STATE_TIMEOUT_MILLIS),
            initialValue = CategoryListUiState(),
        )

    private val _deletionEvents = MutableSharedFlow<Category>(extraBufferCapacity = 1)
    val deletionEvents: SharedFlow<Category> = _deletionEvents.asSharedFlow()

    fun onLongPress(category: Category) {
        viewModelScope.launch {
            // FK record.categoryId → category.id is ON DELETE SET NULL, so any
            // record that used this category becomes "no category" instead of
            // throwing. Re-upserting the same Category restores the row with a
            // new id (autogenerated); records that were SET NULL stay null —
            // imperfect, but matches the Snackbar-undo affordance used elsewhere.
            categoryRepository.deleteById(category.id)
            _deletionEvents.tryEmit(category)
        }
    }

    fun undoDelete(category: Category) {
        viewModelScope.launch {
            categoryRepository.upsert(category.copy(id = 0L))
        }
    }

    private companion object {
        const val STATE_TIMEOUT_MILLIS = 5_000L
    }
}
